apiVersion: v1
kind: ConfigMap
metadata:
  name: wordle-solver-data-config-map
  namespace: {{ namespace }}
data:
{% for key, value in config_values.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}
